import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import CreateTodo from "../components/CreateTodo";
import { api } from "../utils/api";
import TodoList from "../components/TodoList";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>TodoFy | More productive lifestyle</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="text-6xl font-black text-secondary-content">TodoFy</h1>
        <p className="mt-4 mb-10 text-xl font-medium text-primary">
          More productive lifestyle
        </p>
        {sessionData ? (
          <AuthShowcase />
        ) : (
          <button onClick={() => signIn()} className="btn-secondary btn">
            Sign In
          </button>
        )}
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  const { data: todoData } = api.todos.getAll.useQuery();

  return (
    sessionData && (
      <>
        <button onClick={() => signOut()} className="btn-warning btn mb-10">
          Sign Out
        </button>
        <CreateTodo />
        <TodoList todos={todoData || []} />
      </>
    )
  );
};
